version: '3'

services:
  db:
    image: mysql:5.7.32
    container_name: db
    restart: always
    env_file: .env
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - $DB_PATH:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - website-network

  wordpress:
    depends_on:
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - $WP_PATH:/var/www/html
    networks:
      - website-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.18.0
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - $WP_PATH:/var/www/html
      - $NGINX_CONF_PATH:/etc/nginx/conf.d
    networks:
      - website-network
    links:
      - wordpress
      - db

networks:
  website-network:
    driver: bridge
